# action.yml
name: 'Python wheels manylinux build'
author: 'Ralf Gabriels'
description: 'Build manylinux wheels for a (Cython) Python package'
inputs:
  python-versions:
    description: 'Python versions to target, space-separated'
    required: true
    default: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
  build-requirements:
    description: 'pip packages required at build time, space-separated'
    required: false
    default: ''
  system-packages:
    description: 'yum packages to install, space-separated'
    required: false
    default: ''
  pre-build-command:
    description: 'command to run before build, e.g. the execution of a script to perform additional build-environment setup'
    required: false
    default: ''
  build-executable:
    description: 'executable name (relative to python root) for package build'
    required: true
    # default: 'setuptools'
    default: 'pip'
  build-command:
    description: 'command for executable to build package'
    required: true
    # default: 'setup.py bdist_wheel clean' # setuptools
    default: '-w ./dist --no-deps'  # pip
  prebuild-path:
    description: 'path for prebuild operations, relative to repository root'
    required: false
    default: ''
  package-path:
    description: 'path to python package to build, relative to repository root'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.python-versions }}
    - ${{ inputs.build-requirements }}
    - ${{ inputs.system-packages }}
    - ${{ inputs.pre-build-command }}
    - ${{ inputs.build-executable}}
    - ${{ inputs.build-command}}
    - ${{ prebuild-path }}
    - ${{ inputs.package-path }}
branding:
  icon: 'package'
  color: 'green'
