name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.6'
            pep-425-tag: 'cp36-cp36m'
          - python-version: '3.7'
            pep-425-tag: 'cp37-cp37m'
          - python-version: '3.8'
            pep-425-tag: 'cp38-cp38'
          - python-version: '3.9'
            pep-425-tag: 'cp39-cp39'
          - python-version: '3.10'
            pep-425-tag: 'cp310-cp310'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
      with:
        path: test_action
    - name: Checkout hello_py dummy project
      uses: actions/checkout@v2
      with:
        repository: ralfg/hello_py
        ref: v0.1.0
        path: hello_py
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build manylinux Python wheels
      uses: './test_action'
      with:
        python-versions: ${{ matrix.pep-425-tag }}
        build-requirements: 'setuptools numpy cython'
        system-packages: 'gzip'
        pre-build-command: 'echo Hello world! Testing pre-build command'
        package-path: 'hello_py'
    - name: Install wheel
      run: 'pip install hello_py/dist/hello_py*-manylinux*.whl'
    - name: Test wheel
      run: 'hello_py'
